# Copyright 1999-2010 Gentoo Foundation
# Distributed under the terms of the GNU General Public License v2
# This ebuild generated by g-cpan 0.16.4

EAPI="2"

MODULE_AUTHOR="MARKOV"


inherit perl-module

DESCRIPTION="Define a person"

LICENSE="|| ( Artistic GPL-1 GPL-2 GPL-3 )"
SLOT="0"
KEYWORDS="x86 ~x86"
IUSE=""

DEPEND=">=dev-perl/Test-Pod-1.450.0
	dev-lang/perl"
