--- Makefile	2008-02-04 06:48:05.000000000 +0100
+++ Makefile.new	2008-02-05 21:19:27.000000000 +0100
@@ -270,8 +270,8 @@
 	$(strip $(cpp) $(call mkbin,../bsnes) $(objects) $(link))
 
 install:
-	install -m 755 ../bsnes $(prefix)/bin/bsnes
-	install -m 644 data/bsnes.png $(prefix)/share/icons/bsnes.png
+	install -m 755 ../bsnes ${GAMES_BINDIR}
+	install -m 644 data/bsnes.png /usr/share/pixmaps
 
 clean:
 	-@$(call delete,obj/*.$(obj))
